[supervisord]
nodaemon=false
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid
loglevel=info

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
autostart=true
autorestart=true
stderr_logfile=/var/log/nginx/error.log
stdout_logfile=/var/log/nginx/access.log
priority=1
user=www-data

[program:php-fpm]
command=/usr/local/sbin/php-fpm --nodaemonize
autostart=true
autorestart=true
stderr_logfile=/var/log/php-fpm-error.log
stdout_logfile=/var/log/php-fpm.log
priority=2
user=www-data

[program:queue-worker-1]
command=php /var/www/html/spark queue:work --daemon
autostart=true
autorestart=true
stderr_logfile=/var/log/queue-worker-1-error.log
stdout_logfile=/var/log/queue-worker-1.log
priority=10
user=www-data
numprocs=1
process_name=%(program_name)s_%(process_num)02d

[program:queue-worker-2]
command=php /var/www/html/spark queue:work --daemon
autostart=true
autorestart=true
stderr_logfile=/var/log/queue-worker-2-error.log
stdout_logfile=/var/log/queue-worker-2.log
priority=10
user=www-data
numprocs=1
process_name=%(program_name)s_%(process_num)02d

[program:queue-worker-3]
command=php /var/www/html/spark queue:work --daemon
autostart=true
autorestart=true
stderr_logfile=/var/log/queue-worker-3-error.log
stdout_logfile=/var/log/queue-worker-3.log
priority=10
user=www-data
numprocs=1
process_name=%(program_name)s_%(process_num)02d

[program:queue-worker-4]
command=php /var/www/html/spark queue:work --daemon
autostart=true
autorestart=true
stderr_logfile=/var/log/queue-worker-4-error.log
stdout_logfile=/var/log/queue-worker-4.log
priority=10
user=www-data
numprocs=1
process_name=%(program_name)s_%(process_num)02d

[program:redis]
command=/usr/bin/redis-server --appendonly yes
autostart=false
autorestart=true
stderr_logfile=/var/log/redis-error.log
stdout_logfile=/var/log/redis.log
priority=5
user=www-data
